import 'package:equatable/equatable.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:pureair_v2/src/features/air_quality/models/models.dart';

part 'i_aqi.g.dart';

@JsonSerializable()
final class IAqi with EquatableMixin {
  const IAqi({
    this.co,
    this.no2,
    this.o3,
    this.pm10,
    this.so2,
    this.pm25,
    this.pressure,
    this.temperature,
    this.wind,
    this.humidity,
    this.dew,
    this.wg,
  });

  factory IAqi.fromJson(Map<String, dynamic> json) => _$IAqiFromJson(json);

  /// Carbon Monoxide
  ///
  /// A colorless, odorless gas resulting from the incomplete combustion of
  /// fossil fuels (e.g., car emissions, burning coal or wood).
  ///
  /// Measured in parts per million (ppm) or micrograms per
  /// cubic meter (µg/m³).
  final Parameter? co;

  /// Nitrogen Dioxide
  ///
  /// A reddish-brown gas that forms primarily from vehicle emissions and
  /// industrial processes. It contributes to smog and acid rain.
  ///
  /// Measured in parts per billion (ppb) or micrograms
  /// per cubic meter (µg/m³).
  final Parameter? no2;

  /// Ozone
  ///
  /// A gas formed when pollutants like NO2 and volatile organic compounds
  /// (VOCs) react in sunlight. Ground-level ozone is a key component of smog
  /// and can cause respiratory problems.
  ///
  /// Measured in parts per billion (ppb) or micrograms
  /// per cubic meter (µg/m³).
  final Parameter? o3;

  /// Particulate Matter 10
  ///
  /// Coarse particulate matter with a diameter of 10 microns or less,
  /// typically generated by construction dust, road dust, or pollen.
  ///
  /// Measured in micrograms per cubic meter (µg/m³).
  final Parameter? pm10;

  /// Sulfur Dioxide
  ///
  /// A pungent gas produced from burning fossil fuels containing sulfur,
  /// such as coal and oil. It contributes to acid rain and can harm
  /// respiratory health.
  ///
  /// Measured in parts per billion (ppb) or micrograms per cubic
  /// meter (µg/m³).
  final Parameter? so2;

  /// Particulate Matter 2.5 (PM2.5)
  ///
  /// It is measured in micrograms per cubic meter (µg/m³).
  /// PM2.5 refers to fine particles in the air that are 2.5 microns or
  /// smaller, often considered a key indicator of air pollution.
  final Parameter? pm25;

  /// Atmospheric pressure.
  ///
  /// It represents the force exerted by the weight of the air in the
  /// atmosphere.
  @JsonKey(name: 'p')
  final Parameter? pressure;

  /// Temperature.
  ///
  /// It is measured in degrees Celsius (°C). It represents the current
  /// air temperature
  @JsonKey(name: 't')
  final Parameter? temperature;

  /// Wind speed.
  ///
  /// It is measured in meters per second (m/s) or kilometers per hour (km/h).
  /// It indicates how fast the wind is blowing.
  @JsonKey(name: 'w')
  final Parameter? wind;

  /// Humidity, typically expressed as a percentage (%).
  /// It represents the amount of moisture in the air relative to the
  /// maximum it can hold at a given temperature
  @JsonKey(name: 'h')
  final Parameter? humidity;

  /// Dew point temperature.
  ///
  /// It is measured in degrees Celsius (°C).
  /// It indicates the temperature at which air becomes saturated and
  /// condensation begins (e.g., dew or frost forms)
  final Parameter? dew;

  /// Wind gust speed.
  ///
  /// It is measured in meters per second (m/s) or kilometers per hour (km/h).
  /// Wind gusts are sudden, short bursts of stronger wind.
  final Parameter? wg;

  @override
  List<Object?> get props => [
        co,
        no2,
        o3,
        pm10,
        so2,
        pm25,
        pressure,
        temperature,
        wind,
        humidity,
        dew,
        wg
      ];

  IAqi copyWith({
    Parameter? co,
    Parameter? no2,
    Parameter? o3,
    Parameter? pm10,
    Parameter? so2,
    Parameter? pm25,
    Parameter? pressure,
    Parameter? temperature,
    Parameter? wind,
    Parameter? humidity,
    Parameter? dew,
    Parameter? wg,
  }) {
    return IAqi(
      co: co ?? this.co,
      no2: no2 ?? this.no2,
      o3: o3 ?? this.o3,
      pm10: pm10 ?? this.pm10,
      so2: so2 ?? this.so2,
      pm25: pm25 ?? this.pm25,
      pressure: pressure ?? this.pressure,
      temperature: temperature ?? this.temperature,
      wind: wind ?? this.wind,
      humidity: humidity ?? this.humidity,
      dew: dew ?? this.dew,
      wg: wg ?? this.wg,
    );
  }

  Map<String, dynamic> toJson() => _$IAqiToJson(this);
}
