import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:pureair_v2/src/features/aqi/domain/entities/parameter.dart';

part 'iaqi.freezed.dart';
part 'iaqi.g.dart';

@freezed
class IAQI with _$IAQI {
  const factory IAQI({
    /// Carbon Monoxide
    ///
    /// A colorless, odorless gas resulting from the incomplete combustion of
    /// fossil fuels (e.g., car emissions, burning coal or wood).
    ///
    /// Measured in parts per million (ppm) or micrograms per
    /// cubic meter (µg/m³).
    Parameter? co,

    /// Nitrogen Dioxide
    ///
    /// A reddish-brown gas that forms primarily from vehicle emissions and
    /// industrial processes. It contributes to smog and acid rain.
    ///
    /// Measured in parts per billion (ppb) or micrograms
    /// per cubic meter (µg/m³).
    Parameter? no2,

    /// Ozone
    ///
    /// A gas formed when pollutants like NO2 and volatile organic compounds
    /// (VOCs) react in sunlight. Ground-level ozone is a key component of smog
    /// and can cause respiratory problems.
    ///
    /// Measured in parts per billion (ppb) or micrograms
    /// per cubic meter (µg/m³).
    Parameter? o3,

    /// Particulate Matter 10
    ///
    /// Coarse particulate matter with a diameter of 10 microns or less,
    /// typically generated by construction dust, road dust, or pollen.
    ///
    /// Measured in micrograms per cubic meter (µg/m³).
    Parameter? pm10,

    /// Sulfur Dioxide
    ///
    /// A pungent gas produced from burning fossil fuels containing sulfur,
    /// such as coal and oil. It contributes to acid rain and can harm
    /// respiratory health.
    ///
    /// Measured in parts per billion (ppb) or micrograms per cubic
    /// meter (µg/m³).
    Parameter? so2,

    /// Particulate Matter 2.5 (PM2.5)
    ///
    /// It is measured in micrograms per cubic meter (µg/m³).
    /// PM2.5 refers to fine particles in the air that are 2.5 microns or
    /// smaller, often considered a key indicator of air pollution.
    Parameter? pm25,

    /// Atmospheric pressure.
    ///
    /// It represents the force exerted by the weight of the air in the
    /// atmosphere.
    Parameter? pressure,

    /// Temperature.
    ///
    /// It is measured in degrees Celsius (°C). It represents the current
    /// air temperature
    Parameter? temperature,

    /// Wind speed.
    ///
    /// It is measured in meters per second (m/s) or kilometers per hour (km/h).
    /// It indicates how fast the wind is blowing.
    Parameter? wind,

    /// Humidity, typically expressed as a percentage (%).
    /// It represents the amount of moisture in the air relative to the
    /// maximum it can hold at a given temperature
    Parameter? humidity,

    /// Dew point temperature.
    ///
    /// It is measured in degrees Celsius (°C).
    /// It indicates the temperature at which air becomes saturated and
    /// condensation begins (e.g., dew or frost forms)
    Parameter? dew,

    /// Wind gust speed.
    ///
    /// It is measured in meters per second (m/s) or kilometers per hour (km/h).
    /// Wind gusts are sudden, short bursts of stronger wind.
    Parameter? wg,
  }) = _IAQI;

  factory IAQI.fromJson(Map<String, dynamic> json) => _$IAQIFromJson(json);

}
