// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEaOJ7NmaZd8xmF8rzkV_sX7FtH0vpxd0',
    appId: '1:226628641248:web:578ee4d7f3e5f0f4f78b85',
    messagingSenderId: '226628641248',
    projectId: 'pureair-eb5fd',
    authDomain: 'pureair-eb5fd.firebaseapp.com',
    storageBucket: 'pureair-eb5fd.appspot.com',
    measurementId: 'G-XDNTYKS9D6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPKQi4rKr2hwF-XkjqlwBGY9TLQ_J7KfU',
    appId: '1:226628641248:android:5ce176e4e89c0adbf78b85',
    messagingSenderId: '226628641248',
    projectId: 'pureair-eb5fd',
    storageBucket: 'pureair-eb5fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FL0oj8wKW5VJv1qXvMB0q_sdfznU-UI',
    appId: '1:226628641248:ios:f6d6c408bcdc61bef78b85',
    messagingSenderId: '226628641248',
    projectId: 'pureair-eb5fd',
    storageBucket: 'pureair-eb5fd.appspot.com',
    iosBundleId: 'com.example.pureairV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0FL0oj8wKW5VJv1qXvMB0q_sdfznU-UI',
    appId: '1:226628641248:ios:bd60e3ce45139aa6f78b85',
    messagingSenderId: '226628641248',
    projectId: 'pureair-eb5fd',
    storageBucket: 'pureair-eb5fd.appspot.com',
    iosBundleId: 'com.example.pureairV2.RunnerTests',
  );
}
