// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKeoLxR6npcADd8hD6Ii771bwvsp3Cxf4',
    appId: '1:72909982448:web:ca653983decd4e89691035',
    messagingSenderId: '72909982448',
    projectId: 'pureair-f9995',
    authDomain: 'pureair-f9995.firebaseapp.com',
    storageBucket: 'pureair-f9995.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXRCQv7f32PUwgU3dMrFwW0uYxgkYNggM',
    appId: '1:72909982448:android:6e997eee5ef99bfe691035',
    messagingSenderId: '72909982448',
    projectId: 'pureair-f9995',
    storageBucket: 'pureair-f9995.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtbFAJ6aYxsx2o3Y_llfBLAb5BRxRjUF4',
    appId: '1:72909982448:ios:f8f91f4ec9bcf087691035',
    messagingSenderId: '72909982448',
    projectId: 'pureair-f9995',
    storageBucket: 'pureair-f9995.firebasestorage.app',
    iosBundleId: 'com.example.pureairV2',
  );
}
