// Mocks generated by Mockito 5.4.2 from annotations
// in pureair_v2/test/facades/weather_facade_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:pureair_v2/infrastructure/infrastructure.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherDto_0 extends _i1.SmartFake implements _i2.WeatherDto {
  _FakeWeatherDto_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDatasource extends _i1.Mock
    implements _i2.WeatherRemoteDatasource {
  @override
  _i3.Future<_i2.WeatherDto> getWeather({
    required double? lat,
    required double? lon,
    String? exclude,
    String? units,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [],
          {
            #lat: lat,
            #lon: lon,
            #exclude: exclude,
            #units: units,
          },
        ),
        returnValue: _i3.Future<_i2.WeatherDto>.value(_FakeWeatherDto_0(
          this,
          Invocation.method(
            #getWeather,
            [],
            {
              #lat: lat,
              #lon: lon,
              #exclude: exclude,
              #units: units,
            },
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i2.WeatherDto>.value(_FakeWeatherDto_0(
          this,
          Invocation.method(
            #getWeather,
            [],
            {
              #lat: lat,
              #lon: lon,
              #exclude: exclude,
              #units: units,
            },
          ),
        )),
      ) as _i3.Future<_i2.WeatherDto>);
}

/// A class which mocks [WeatherMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherMapper extends _i1.Mock implements _i2.WeatherMapper {}
