import 'package:cv/cv.dart';
import 'package:equatable/equatable.dart';
import 'package:pureair_v2/src/features/air_quality/repository/datasources/dtos/parameter_dto.dart';

final class IAqiDto extends CvModelBase with EquatableMixin {
  IAqiDto();

  factory IAqiDto.fromJson(Map<String, dynamic> map) {
    final value = map.cv<IAqiDto>();
    return value;
  }

  /// Carbon Monoxide
  ///
  /// A colorless, odorless gas resulting from the incomplete combustion of
  /// fossil fuels (e.g., car emissions, burning coal or wood).
  ///
  /// Measured in parts per million (ppm) or micrograms per
  /// cubic meter (µg/m³).
  final co = CvModelField<ParameterDto>.builder('co');

  /// Nitrogen Dioxide
  ///
  /// A reddish-brown gas that forms primarily from vehicle emissions and
  /// industrial processes. It contributes to smog and acid rain.
  ///
  /// Measured in parts per billion (ppb) or micrograms
  /// per cubic meter (µg/m³).
  final no2 = CvModelField<ParameterDto>.builder('no2');

  /// Ozone
  ///
  /// A gas formed when pollutants like NO2 and volatile organic compounds
  /// (VOCs) react in sunlight. Ground-level ozone is a key component of smog
  /// and can cause respiratory problems.
  ///
  /// Measured in parts per billion (ppb) or micrograms
  /// per cubic meter (µg/m³).
  final o3 = CvModelField<ParameterDto>.builder('o3');

  /// Particulate Matter 10
  ///
  /// Coarse particulate matter with a diameter of 10 microns or less,
  /// typically generated by construction dust, road dust, or pollen.
  ///
  /// Measured in micrograms per cubic meter (µg/m³).
  final pm10 = CvModelField<ParameterDto>.builder('pm10');

  /// Sulfur Dioxide
  ///
  /// A pungent gas produced from burning fossil fuels containing sulfur,
  /// such as coal and oil. It contributes to acid rain and can harm
  /// respiratory health.
  ///
  /// Measured in parts per billion (ppb) or micrograms per cubic
  /// meter (µg/m³).
  final so2 = CvModelField<ParameterDto>.builder('so2');

  /// Particulate Matter 2.5 (PM2.5)
  ///
  /// It is measured in micrograms per cubic meter (µg/m³).
  /// PM2.5 refers to fine particles in the air that are 2.5 microns or
  /// smaller, often considered a key indicator of air pollution.
  final pm25 = CvModelField<ParameterDto>.builder('pm25');

  /// Atmospheric pressure.
  ///
  /// It represents the force exerted by the weight of the air in the
  /// atmosphere.
  final pressure = CvModelField<ParameterDto>.builder('p');

  /// Temperature.
  ///
  /// It is measured in degrees Celsius (°C). It represents the current
  /// air temperature
  final temperature = CvModelField<ParameterDto>.builder('t');

  /// Wind speed.
  ///
  /// It is measured in meters per second (m/s) or kilometers per hour (km/h).
  /// It indicates how fast the wind is blowing.
  final wind = CvModelField<ParameterDto>.builder('w');

  /// Humidity, typically expressed as a percentage (%).
  /// It represents the amount of moisture in the air relative to the
  /// maximum it can hold at a given temperature
  final humidity = CvModelField<ParameterDto>.builder('h');

  /// Dew point temperature.
  ///
  /// It is measured in degrees Celsius (°C).
  /// It indicates the temperature at which air becomes saturated and
  /// condensation begins (e.g., dew or frost forms)
  final dew = CvModelField<ParameterDto>.builder('dew');

  /// Wind gust speed.
  ///
  /// It is measured in meters per second (m/s) or kilometers per hour (km/h).
  /// Wind gusts are sudden, short bursts of stronger wind.
  final wg = CvModelField<ParameterDto>.builder('wg');

  @override
  List<CvField> get fields => [
        co,
        no2,
        o3,
        pm10,
        so2,
        pm25,
        pressure,
        temperature,
        wind,
        humidity,
        dew,
        wg,
      ];

  @override
  List<Object?> get props => [
        co,
        no2,
        o3,
        pm10,
        so2,
        pm25,
        pressure,
        temperature,
        wind,
        humidity,
        dew,
        wg,
      ];
}
